"""initial schema

Revision ID: 499da650c43f
Revises: 
Create Date: 2026-08-04 21:58:54.735453
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '499da650c43f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('session_token', sa.String(length=64), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('album',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('cover_photo_id', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('lang', sa.String(length=5), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('russian', coalesce(title, '')), 'A') || setweight(to_tsvector('russian', coalesce(caption, '')), 'B')", persisted=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cover_photo_id'], ['photo.id'], name='fk_album_cover_photo', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_album_is_published'), 'album', ['is_published'], unique=False)
    op.create_index('ix_album_search', 'album', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_album_sort_order'), 'album', ['sort_order'], unique=False)
    op.create_table('login_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_attempt_attempted_at'), 'login_attempt', ['attempted_at'], unique=False)
    op.create_index(op.f('ix_login_attempt_ip'), 'login_attempt', ['ip'], unique=False)
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('body_md', sa.Text(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('cover_path', sa.String(length=300), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', name='poststatus', native_enum=False, length=16), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lang', sa.String(length=5), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('russian', coalesce(title, '')), 'A') || setweight(to_tsvector('russian', coalesce(excerpt, '')), 'B') || setweight(to_tsvector('russian', coalesce(body_md, '')), 'C')", persisted=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_post_published_at'), 'post', ['published_at'], unique=False)
    op.create_index('ix_post_search', 'post', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_post_status'), 'post', ['status'], unique=False)
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('body_md', sa.Text(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('repo_url', sa.String(length=500), nullable=True),
    sa.Column('demo_url', sa.String(length=500), nullable=True),
    sa.Column('tech_stack', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('cover_path', sa.String(length=300), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('lang', sa.String(length=5), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('russian', coalesce(title, '')), 'A') || setweight(to_tsvector('russian', coalesce(summary, '')), 'B') || setweight(to_tsvector('russian', coalesce(body_md, '')), 'C')", persisted=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_project_is_published'), 'project', ['is_published'], unique=False)
    op.create_index('ix_project_search', 'project', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_project_sort_order'), 'project', ['sort_order'], unique=False)
    op.create_table('site_content',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('lang', sa.String(length=5), nullable=False),
    sa.Column('value_md', sa.Text(), nullable=False),
    sa.Column('value_html', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key', 'lang')
    )
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('original_path', sa.String(length=300), nullable=False),
    sa.Column('thumb_path', sa.String(length=300), nullable=True),
    sa.Column('medium_path', sa.String(length=300), nullable=True),
    sa.Column('large_path', sa.String(length=300), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('alt', sa.String(length=300), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'ready', 'failed', name='photostatus', native_enum=False, length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_album_id'), 'photo', ['album_id'], unique=False)
    op.create_index(op.f('ix_photo_sort_order'), 'photo', ['sort_order'], unique=False)
    op.create_index(op.f('ix_photo_status'), 'photo', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photo_status'), table_name='photo')
    op.drop_index(op.f('ix_photo_sort_order'), table_name='photo')
    op.drop_index(op.f('ix_photo_album_id'), table_name='photo')
    op.drop_table('photo')
    op.drop_table('site_content')
    op.drop_index(op.f('ix_project_sort_order'), table_name='project')
    op.drop_index('ix_project_search', table_name='project', postgresql_using='gin')
    op.drop_index(op.f('ix_project_is_published'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_post_status'), table_name='post')
    op.drop_index('ix_post_search', table_name='post', postgresql_using='gin')
    op.drop_index(op.f('ix_post_published_at'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_login_attempt_ip'), table_name='login_attempt')
    op.drop_index(op.f('ix_login_attempt_attempted_at'), table_name='login_attempt')
    op.drop_table('login_attempt')
    op.drop_index(op.f('ix_album_sort_order'), table_name='album')
    op.drop_index('ix_album_search', table_name='album', postgresql_using='gin')
    op.drop_index(op.f('ix_album_is_published'), table_name='album')
    op.drop_table('album')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
